export const ADD_NEW_TODO = 'ADD_NEW_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const COMPLETED_TODO = 'COMPLETED_TODO'
export const TOGGLE_COMPLETED_ALL_TODO = 'TOGGLE_COMPLETED_ALL_TODO'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'

